<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/Services/PatientRegistry/PulseGuard.PatientRegistry.Application/PulseGuard.PatientRegistry.Application.csproj" />
    <ProjectReference Include="../../src/Services/PatientRegistry/PulseGuard.PatientRegistry.Domain/PulseGuard.PatientRegistry.Domain.csproj" />
  </ItemGroup>
</Project>
