<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <ProjectReference Include="../../../BuildingBlocks/PulseGuard.Framework.Messaging.EntityFrameworkCore/PulseGuard.Framework.Messaging.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../PulseGuard.Telemetry.Application/PulseGuard.Telemetry.Application.csproj" />
    <ProjectReference Include="../PulseGuard.Telemetry.Domain/PulseGuard.Telemetry.Domain.csproj" />
  </ItemGroup>
</Project>
