<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoNSubstitute" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/Services/PatientRegistry/PulseGuard.PatientRegistry.Infrastructure/PulseGuard.PatientRegistry.Infrastructure.csproj" />
  </ItemGroup>
</Project>
